import { Cinzel_Decorative, Inter } from "next/font/google";
import "./globals.css";

const titleFont = Cinzel_Decorative({ variable: "--font-title", subsets: ["latin"], weight: ["400","700"], display: "swap" });
const bodyFont = Inter({ variable: "--font-body", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${titleFont.variable} ${bodyFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
